feat: new container added
Kush-Wednesday/next-bulletproof-ts pull request #1
Opened 2022-08-05 09:58 UTC by Kush-Wednesday

fetched data from itunes api and rendering it.

2022-08-05 10:20 UTC, christin-wednesday commented
please add a description, and screenshots (large and small breakpoints)

2022-08-05 10:25 UTC, christin-wednesday requested changes

2022-08-05 10:25 UTC, christin-wednesday commented on containers/itunes/index.tsx
> +  const { data, error, isLoading, isFetching } = useFetchSongQuery("Better");
we should use the data variable from the hook instead of a separate state variable.

2022-08-05 10:25 UTC, christin-wednesday commented on features/itunes/api/getSongs.tsx
> +      query: name => `search?term=${name}`,
this api call should only be made if name is defined.

2022-08-05 10:25 UTC, christin-wednesday commented on store/slices/itunes.ts
> +  export default ituneSlice.reducer;
https://www.computerhope.com/jargon/e/eof.htm

2022-08-05 10:25 UTC, christin-wednesday commented on features/itunes/api/getSongs.tsx
> +  artistId:number;
please setup auto formatting.

2022-08-08 05:03 UTC, Kush-Wednesday commented
Added itunes container which makes api call to get songs from itunes  based on search from the user.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/110533416/183342797-ab0f953e-bec1-40c5-933e-0681f405a131.png">

2.
<img width="873" alt="image" src="https://user-images.githubusercontent.com/110533416/183342916-d3062eb8-1fc1-47cd-8c53-e50a59758b2d.png">

2022-08-08 05:21 UTC, christin-wednesday commented on containers/itunes/index.tsx
> +        onSearch={searchText => handleOnChange(searchText)}
when is onSearch triggered ?

2022-08-08 05:22 UTC, christin-wednesday approved these changes

2022-08-08 05:31 UTC, merged